spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: "dd-MM-yyyy HH:mm:ss"
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    # for test case scenario: ddl-auto: drop-and-create
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/microblog
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    lt:
      karijotas: DEBUG
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: DEBUG
Server:
  Port: 8080