spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: "dd-MM-yyyy HH:mm:ss"
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/microblog
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    lt:
      karijotas: DEBUG
    org:
      springframework: INFO
Server:
  Port: 8080