CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    body       TEXT,
    blogger_id BIGINT                                  NOT NULL,
    count      INT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE blogger
  (
      blogger_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      user_name  VARCHAR(255),
      password   VARCHAR(255),
      CONSTRAINT pk_blogger PRIMARY KEY (blogger_id)
  );

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_BLOGGER FOREIGN KEY (blogger_id) REFERENCES blogger (blogger_id);