CREATE TABLE comment
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    comment  VARCHAR(255),
    post_id  BIGINT,
    user_id  BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    body    VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_comment_list
(
    post_id         BIGINT NOT NULL,
    comment_list_id BIGINT NOT NULL
);

CREATE TABLE "user"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_post_list
(
    user_id      BIGINT NOT NULL,
    post_list_id BIGINT NOT NULL
);

ALTER TABLE post_comment_list
    ADD CONSTRAINT uc_post_comment_list_commentlist UNIQUE (comment_list_id);

ALTER TABLE user_post_list
    ADD CONSTRAINT uc_user_post_list_postlist UNIQUE (post_list_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE post_comment_list
    ADD CONSTRAINT fk_poscomlis_on_comment FOREIGN KEY (comment_list_id) REFERENCES comment (id);

ALTER TABLE post_comment_list
    ADD CONSTRAINT fk_poscomlis_on_post FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE user_post_list
    ADD CONSTRAINT fk_useposlis_on_post FOREIGN KEY (post_list_id) REFERENCES post (id);

ALTER TABLE user_post_list
    ADD CONSTRAINT fk_useposlis_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);
