INSERT INTO post (name, body, blogger_id, count)
VALUES ('Repeated Words Example',
        'This example contains repeated words. Repeated words can emphasize certain aspects of the text and aid in conveying a specific message. The repetition of words is intentional in this example.',
        1, 0),
       ('AI Advancements',
        'Researchers have developed a groundbreaking AI algorithm that revolutionizes data analysis techniques, paving the way for enhanced predictive models and automated decision-making processes.',
        1, 0),
       ('Blockchain Innovations',
        'The latest advancements in blockchain technology promise increased security and scalability, offering new opportunities for decentralized applications and secure digital transactions.',
        2, 0),
       ('Cybersecurity Trends',
        'Amid rising cyber threats, cybersecurity experts unveil new strategies and tools to fortify networks and protect sensitive data against evolving cyber attacks.',
        3, 0),
       ('Cloud Computing Updates',
        'Cloud computing witnesses rapid growth with the introduction of innovative cloud services, enabling businesses to optimize operations and enhance scalability.',
        4, 0),
       ('Quantum Computing Breakthroughs',
        'The quantum computing frontier expands as researchers achieve major milestones, bringing us closer to solving complex problems faster than ever.',
        5, 0);
