INSERT INTO comment (post_id, content)
VALUES (1, 'This is a great post! I really enjoyed reading it.'),
       (1, 'Nice job on explaining complex concepts.'),
       (1, 'Looking forward to more content like this.'),
       (2, 'Interesting perspectives shared in this article.'),
       (2, 'The content is quite informative.'),
       (2, 'I found some parts confusing. Can you clarify?'),
       (3, 'I have a question about the topic discussed.'),
       (3, 'Could you elaborate more on this particular aspect?'),
       (3, 'I disagree with some points but overall a good read.'),
       (4, 'The post was a bit hard to follow.'),
       (4, 'I found some parts confusing. Can you clarify?'),
       (4, 'Nice job on explaining complex concepts.'),
       (5, 'The content is quite informative.'),
       (5, 'I have a question about the topic discussed.'),
       (5, 'This is a great post! I really enjoyed reading it.'),
       (4, 'Could you elaborate more on this particular aspect?'),
       (2, 'I disagree with some points but overall a good read.'),
       (1, 'Interesting perspectives shared in this article.'),
       (1, 'Looking forward to more content like this.'),
       (2, 'I found some parts confusing. Can you clarify?'),
       (2, 'The post was a bit hard to follow.'),
       (3, 'Nice job on explaining complex concepts.'),
       (4, 'I have a question about the topic discussed.'),
       (5, 'This is a great post! I really enjoyed reading it.'),
       (1, 'The content is quite informative.'),
       (2, 'I disagree with some points but overall a good read.'),
       (3, 'Interesting perspectives shared in this article.'),
       (5, 'I found some parts confusing. Can you clarify?'),
       (4, 'Nice job on explaining complex concepts.'),
       (2, 'Looking forward to more content like this.');
